#!/bin/bash

err() {
	echo $1
	usage
	exit
}

usage() {
	cat <<EOF

Usage: xdg-open [file|directory|protocol]

It opens a file according to the extension
To setup the extension, create ~/.config/mimi/mime.conf
e.g.
	default:urxvt -e ranger
	pdf:mupdf
	ftp:filezilla
mimi :)
EOF
}

find_program() {
	grep "^$1:" "$CONFIG" | cut -d : -f 2
}

CONFIG="$HOME/.config/mimi/mime.conf"
[[ -f "$CONFIG" ]] || err "No configuration file found."

arg="$@"
program=""

if [[ "$arg" =~ "^([a-zA-Z]+):" ]]; then
	# handle protocol
	protocol=${BASH_REMATCH[1]}
	program=$(find_program "$protocol")
elif [[ -f "$arg" ]]; then
	# handle file
	filename="$@"
	ext="${filename##*.}"
	program=$(find_program "$ext")
elif [[ -d "$arg" ]]; then
	# handle directory
	program=$(find_program directory)
else
	err "File or directory not found: $arg"
fi

if [[ "$program" == "" ]]; then
	# default
	program=$(find_program default)
fi

$program "$arg"